name: workflow
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: invoke script
        run: chmod +x action-a/entrypoint.sh
        run: sh action-a/entrypoint.sh
        shell: bash
